"""initial schema

Revision ID: c78299663cf2
Revises:
Create Date: 2026-07-17 01:47:19.635202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c78299663cf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('buyer_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('regions', sa.String(length=255), nullable=True),
    sa.Column('care_types', sa.String(length=255), nullable=True),
    sa.Column('min_turnover', sa.String(length=50), nullable=True),
    sa.Column('max_turnover', sa.String(length=50), nullable=True),
    sa.Column('min_beds', sa.Integer(), nullable=True),
    sa.Column('max_beds', sa.Integer(), nullable=True),
    sa.Column('funding_ready', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_id')
    )
    op.create_table('buyer_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('care_type', sa.String(length=100), nullable=True),
    sa.Column('min_price_band', sa.String(length=50), nullable=True),
    sa.Column('max_price_band', sa.String(length=50), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('investment_type', sa.String(length=50), nullable=True),
    sa.Column('deal_structure', sa.String(length=50), nullable=True),
    sa.Column('min_budget', sa.String(length=50), nullable=True),
    sa.Column('max_budget', sa.String(length=50), nullable=True),
    sa.Column('proof_of_funds', sa.String(length=20), nullable=True),
    sa.Column('preferred_multiple', sa.String(length=50), nullable=True),
    sa.Column('funding_source', sa.String(length=50), nullable=True),
    sa.Column('preferred_regions', sa.String(length=255), nullable=True),
    sa.Column('care_types', sa.String(length=255), nullable=True),
    sa.Column('beds_min', sa.Integer(), nullable=True),
    sa.Column('beds_max', sa.Integer(), nullable=True),
    sa.Column('quality_preference', sa.String(length=100), nullable=True),
    sa.Column('turnaround_interest', sa.String(length=50), nullable=True),
    sa.Column('transaction_timeline', sa.String(length=50), nullable=True),
    sa.Column('expansion_strategy', sa.Text(), nullable=True),
    sa.Column('has_buy_side_advisor', sa.Boolean(), nullable=True),
    sa.Column('advisor_details', sa.Text(), nullable=True),
    sa.Column('requirements_dd', sa.String(length=255), nullable=True),
    sa.Column('nda_signed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('listing_code', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('care_type', sa.String(length=100), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('occupancy_percent', sa.Integer(), nullable=True),
    sa.Column('cqc_rating', sa.String(length=50), nullable=True),
    sa.Column('tenure', sa.String(length=50), nullable=True),
    sa.Column('revenue_band', sa.String(length=50), nullable=True),
    sa.Column('ebitda_band', sa.String(length=50), nullable=True),
    sa.Column('guide_price_band', sa.String(length=50), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('is_confidential', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('photo_filename', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_code')
    )
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_status'), ['status'], unique=False)

    op.create_table('page_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('stripe_payment_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    op.create_table('seller_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('turnover', sa.String(length=100), nullable=True),
    sa.Column('ebitda', sa.String(length=100), nullable=True),
    sa.Column('profit', sa.String(length=100), nullable=True),
    sa.Column('loss', sa.String(length=100), nullable=True),
    sa.Column('assets', sa.String(length=255), nullable=True),
    sa.Column('debts', sa.String(length=255), nullable=True),
    sa.Column('staff_count', sa.Integer(), nullable=True),
    sa.Column('regions', sa.String(length=255), nullable=True),
    sa.Column('care_type', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('nda_accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('renews_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('valuer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('accreditation', sa.String(length=255), nullable=True),
    sa.Column('regions', sa.String(length=255), nullable=True),
    sa.Column('pricing_notes', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('enquiry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('nda_accepted', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enquiry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enquiry_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enquiry_listing_id'), ['listing_id'], unique=False)

    op.create_table('financials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('turnover', sa.String(length=100), nullable=True),
    sa.Column('ebitda', sa.String(length=100), nullable=True),
    sa.Column('profit', sa.String(length=100), nullable=True),
    sa.Column('loss', sa.String(length=100), nullable=True),
    sa.Column('assets', sa.String(length=255), nullable=True),
    sa.Column('debts', sa.String(length=255), nullable=True),
    sa.Column('staff_count', sa.Integer(), nullable=True),
    sa.Column('year_end', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id')
    )
    op.create_table('introductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('offer_amount', sa.String(length=100), nullable=True),
    sa.Column('offer_date', sa.DateTime(), nullable=True),
    sa.Column('offer_terms', sa.Text(), nullable=True),
    sa.Column('funding_confirmed', sa.Boolean(), nullable=True),
    sa.Column('heads_of_terms_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_id', 'seller_id', 'listing_id', name='uq_introduction_parties_listing')
    )
    with op.batch_alter_table('introductions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_introductions_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_introductions_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_introductions_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_introductions_status'), ['status'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('buyer_name', sa.String(length=200), nullable=False),
    sa.Column('buyer_email', sa.String(length=200), nullable=False),
    sa.Column('buyer_phone', sa.String(length=100), nullable=True),
    sa.Column('buyer_company', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_listing_id'), ['listing_id'], unique=False)

    op.create_table('listing_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_photo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_photo_listing_id'), ['listing_id'], unique=False)

    op.create_table('seller_profile_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['seller_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seller_profile_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seller_profile_documents_profile_id'), ['profile_id'], unique=False)

    op.create_table('valuation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('valuer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['valuer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('valuation_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valuation_requests_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_valuation_requests_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_valuation_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_valuation_requests_valuer_id'), ['valuer_id'], unique=False)

    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('introduction_id', sa.Integer(), nullable=False),
    sa.Column('agreed_price', sa.String(length=100), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('broker_commission_percent', sa.Float(), nullable=True),
    sa.Column('broker_commission_amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['introduction_id'], ['introductions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('introduction_id')
    )
    op.create_table('introduction_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('introduction_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['introduction_id'], ['introductions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('introduction_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_introduction_status_history_introduction_id'), ['introduction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('introduction_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_introduction_status_history_introduction_id'))

    op.drop_table('introduction_status_history')
    op.drop_table('deals')
    with op.batch_alter_table('valuation_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valuation_requests_valuer_id'))
        batch_op.drop_index(batch_op.f('ix_valuation_requests_status'))
        batch_op.drop_index(batch_op.f('ix_valuation_requests_seller_id'))
        batch_op.drop_index(batch_op.f('ix_valuation_requests_listing_id'))

    op.drop_table('valuation_requests')
    with op.batch_alter_table('seller_profile_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seller_profile_documents_profile_id'))

    op.drop_table('seller_profile_documents')
    with op.batch_alter_table('listing_photo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_photo_listing_id'))

    op.drop_table('listing_photo')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_listing_id'))

    op.drop_table('leads')
    with op.batch_alter_table('introductions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_introductions_status'))
        batch_op.drop_index(batch_op.f('ix_introductions_seller_id'))
        batch_op.drop_index(batch_op.f('ix_introductions_listing_id'))
        batch_op.drop_index(batch_op.f('ix_introductions_buyer_id'))

    op.drop_table('introductions')
    op.drop_table('financials')
    with op.batch_alter_table('enquiry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enquiry_listing_id'))
        batch_op.drop_index(batch_op.f('ix_enquiry_buyer_id'))

    op.drop_table('enquiry')
    op.drop_table('valuer_profiles')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))

    op.drop_table('subscriptions')
    op.drop_table('seller_profiles')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))

    op.drop_table('payments')
    op.drop_table('page_content')
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_status'))
        batch_op.drop_index(batch_op.f('ix_listing_seller_id'))

    op.drop_table('listing')
    op.drop_table('buyer_profile')
    op.drop_table('buyer_criteria')
    op.drop_table('user')
    # ### end Alembic commands ###
